### ISSUE TITLE
Package [com.google.external-dependency-manager@1.2.170] cannot be found

### ISSUE THREAD

**Issue by qq762278029** [Thaina/play-games-plugin-for-unity#1]
My current version of ExternalDependencyManager is 1.2.180
The latest version of ExternalDependency Manager is 1.2.181
https://github.com/google-unity/external-dependency-manager/releases

When I tried to import this plugin, an error occurred:
Package [com.google.external-dependency-manager@1.2.170] cannot be found

This is all the error logs:
[Package Manager Window] Error adding package: https://github.com/Thaina/play-games-plugin-for-unity.git?path=/Assets/Public/GooglePlayGames/com.google.play.games.
Unable to add package [https://github.com/Thaina/play-games-plugin-for-unity.git?path=/Assets/Public/GooglePlayGames/com.google.play.games]:
  Package com.google.play.games@https://github.com/Thaina/play-games-plugin-for-unity.git?path=/Assets/Public/GooglePlayGames/com.google.play.games has invalid dependencies or related test packages:
    com.google.external-dependency-manager (dependency): Package [com.google.external-dependency-manager@1.2.170] cannot be found
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Volumes/jenkins1/sharedspace/ra_2022.3/Editor/Mono/EditorApplication.cs:381)

**Comment by Thaina** [comment]
I would like to ask how did you add ExternalDependencyManager in your project?

Did you have it as folder, or using UPM in some way

Could you please try config your dependencies like this?

```JSON
{
  "dependencies": {
    "com.google.external-dependency-manager": "https://github.com/googlesamples/unity-jar-resolver.git?path=upm",
    "com.google.play.games": "https://github.com/Thaina/play-games-plugin-for-unity.git?path=/Assets/Public/GooglePlayGames/com.google.play.games",
    ...
  }
}
```

**Comment by qq762278029** [comment]
[as folder]
Unfortunately, my project used Firebase and Admob for importing through unitypackage.
ExternalDependencyManager is imported together with the unitypackage.

**Comment by Thaina** [comment]
Then that would not work properly with UPM package dependencies system

However I recommend that you can just add `com.google.external-dependency-manager` in to the `manifest.json` as above then just remove `ExternalDependencyManager` folder from your asset. Firebase and admob can use it from package folder too

And when you import unitypackage file you actually have option to uncheck importing folder that you already have in package project, `ExternalDependencyManager` is one of them

I would like to suggest that you should also remove both firebase and admob from your asset folder, and import admob as upm git like above. Firebase can also be imported as tgz (import tarball option in UPM)

**Comment by Thaina** [comment]
And if you truly need to keep everything in asset folder, you might just clone this repo and copy folder `/Assets/Public/GooglePlayGames/com.google.play.games` from this repo into your asset project

**Comment by qq762278029** [comment]
I removed ExternalDependencyManager folder from my asset.
Everything works normally after adding the following code:
`{
  "dependencies": {
    "com.google.external-dependency-manager": "https://github.com/googlesamples/unity-jar-resolver.git?path=upm",
    "com.google.play.games": "https://github.com/Thaina/play-games-plugin-for-unity.git?path=/Assets/Public/GooglePlayGames/com.google.play.games",
  }
}`

Thank you very much for your help, it really helped me a lot.
